### Docker - Consulta Extrato
GET  http://localhost:9999/clientes/2/extrato


### Docker - Cadastro Transação
POST http://localhost:9999/clientes/1/transacoes
Content-Type: application/json

{
    "valor": 1000,
    "descricao": "descricao",
    "tipo": "d"
}






### Local - Consulta Extrato
GET  http://localhost:8000/clientes/4/extrato


### Local - Cadastro Transação
POST http://localhost:8000/clientes/4/transacoes
Content-Type: application/json

{
    "valor": 1,
    "descricao": "tome",
    "tipo": "d"
}
